@extends('frontend_layouts.partials.inner_layout')
@extends('frontend_layouts.partials.header')
@extends('frontend_layouts.partials.sidebar')
@extends('frontend_layouts.partials.footer')

@section('content')  

  <div class="maincontent">
                <section class="section">
    <div class="container">
		<div class="col-md-12 mycontainer">
		    <div class="page-heading">
		        <div class="widget">
		            <h2 class="title-border"><p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 16pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">About Us </span></strong></p></h2>
		        </div>
		    </div>
		       

<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tests are like mirrors which reflect your performance. There are various options available for students to prepare for MCA Entrance but the question is &ndash; which medium assures your success completely ? We are not claiming that we are the only institution Which can help you cracking the </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MCA Entrance Exam</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> but yes we can assure you that we &nbsp;provide the best study material and the best test series &nbsp;for outstanding preparation of students . here are the reasons which makes our test series different as well as efficient </span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Regular &nbsp;Tests</span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;Regularity sounds simple but it takes a lot of guts to conduct test series on regular basis. Bad weather conditions, personal &nbsp;problems, health related issues , national holiday etc . never hamper the regularity of </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> test series. </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> conducts test on each and every single day of its academic year &nbsp;.</span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Covering the wide- range of syllabus which can help you crack not only one specific examination but also other prominent similar examinations .</span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;The speciality of </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> test series is that it never considers any topic as unimportant you will get a chance to give attempt a well-set question paper if even those topic which are rarely asked in examination . But as we have seen in past few years that the paper pattern is not always predictable , therefore MaaRula Classes tries to prepare it&rsquo;s students for all kinds of possibilities . </span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Separate Model paper for BHU/ JNU/ NIMCET and other important Entrance examinations</span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Students always ask for model papers so that they can get some idea about the paper pattern followed in the specific examination . </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> not only fulfills this demand of students by conducting model paper test series but also builds up students confidence level by increasing its frequency of tests to number which no other institute can match easily .</span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Best way of Revision by conducting topic wise test- series </span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Before coming to model papers </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> conducts topic &ndash;wise test series whose frequency is so large that if the students continues to solve the whole test paper and finds out the answer key of all the questions honestly then he/ she can secure a good rank in </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">NIMCET</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> or any other central university Entrance examination easily .</span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">All the important questions asked in different MCA- Entrance examination are shuffled test-paper of MaaRula Classes in a very efficient &ndash;manner </span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> tries to bring all the aspects of competitive world before it&rsquo;s students . the test papers cover all the important question which have been asked in previous year examinations. It also cover all the other similar kind of problems which can come in the next year question paper . </span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Equal Attention paid to Mathematics / English / Aptitude / Reasoning </span></strong></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Students always hear that mathematics covers large portion &nbsp;&nbsp;in </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">NIMCET </span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">or reasoning covers more portion in JNU or don&rsquo;t care about aptitude and computer of your target is BHU and many other rumors. Students usually believe such rumors &nbsp;and put their 100% effort on usually one portion but the question is What if the paper pattern changes completely in the coming paper or even if it doesn&rsquo;t change and you qualify your Entrance successfully , can you also grab your job with the same preparation tactics . the answer in &lsquo;No&rsquo; because if you want to perform well in your Entrance as well as in your Institution &nbsp;in which you will pursue your 3-year MCA program then you will have to focus on all these topics dynamically .</span></p>
<p style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify;"><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> And so </span><strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MaaRula</span></strong> <strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Classes</span></strong><span style="font-size: 11pt; font-family: Cambria; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> conducts regular test on all these subjects which helps its students in giving &nbsp;outstanding results . </span></p>
<p>&nbsp;</p>       
		</div>
	</div>
</section>        </div>

        </div>
</div>
@endsection